### ISSUE TITLE
Some parts of the documentation are in Spanish 😅

### ISSUE THREAD

**Issue by marinaaisa** [mendesaltaren/product-design-handbook-en#1]
I guess you forgot to translate these parts:

- From [Prototyping](https://productdesignhandbook.mendesaltaren.com/process#4-2-prototyping) section onwards.

- `Documentación` title at https://productdesignhandbook.mendesaltaren.com/design-systems#6-documentacion

:)

**Comment by guerrero** [comment]
Sorry @marinaaisa, we reviewed this issue two years ago but somehow I forgot to answer you so I think that our "Spanglish" problem has been overtaken by this one in the list of the most embarrasing issues of the repo 😅.

Thanks again for letting us know about this problem.
